import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import { ReactNode } from 'react'

import { ApolloClientProvider } from '@/providers/ApolloClientProvider'
import { ToastProvider } from '@/providers/ToastProvider'

import '@/styles/globals.css'

const geist = Geist({
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default async function RootLayout({
	children
}: Readonly<{
	children: ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${geist.className} antialiased`}>
				<ApolloClientProvider>
					<ToastProvider />
					{children}
				</ApolloClientProvider>
			</body>
		</html>
	)
}
